export type ScopeOfWorkItem = {
  id: string;
  projectId: string;
  scope: string;
  group: string;
  percent: number;
  source: string;
  updateMode: "Input scopes" | "Copy/paste template" | "Approved site manager scan";
  approvedBy: string;
  approvedDate: string;
  approvalFileUrl: string;
};

export type DeployedTool = {
  id: string;
  projectId: string;
  name: string;
  folderUrl: string;
  imageLabel: string;
  deployedDate: string;
  status: "Deployed" | "For Return" | "Returned";
};

export const scopeOfWorkItems: ScopeOfWorkItem[] = [
  {
    id: "SOW-001",
    projectId: "dimaano-residences",
    scope: "General Requirements",
    group: "General Scope",
    percent: 18,
    source: "Dimaano Residences BOM",
    updateMode: "Approved site manager scan",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-002",
    projectId: "dimaano-residences",
    scope: "Government Permits",
    group: "General Requirements",
    percent: 10,
    source: "Dimaano Residences BOM",
    updateMode: "Copy/paste template",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-003",
    projectId: "dimaano-residences",
    scope: "Temporary Facilities",
    group: "General Requirements",
    percent: 24,
    source: "Dimaano Residences BOM",
    updateMode: "Input scopes",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-004",
    projectId: "dimaano-residences",
    scope: "Site In Charge - Supervision and Office Support",
    group: "General Requirements",
    percent: 15,
    source: "Dimaano Residences BOM",
    updateMode: "Input scopes",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-005",
    projectId: "dimaano-residences",
    scope: "Mobilization, Demobilization, Closeout",
    group: "General Requirements",
    percent: 12,
    source: "Dimaano Residences BOM",
    updateMode: "Copy/paste template",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-006",
    projectId: "dimaano-residences",
    scope: "Siteworks",
    group: "General Scope",
    percent: 12,
    source: "Dimaano Residences BOM",
    updateMode: "Approved site manager scan",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-007",
    projectId: "dimaano-residences",
    scope: "Building Preparation and Excavation",
    group: "Siteworks",
    percent: 20,
    source: "Dimaano Residences BOM",
    updateMode: "Approved site manager scan",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-008",
    projectId: "dimaano-residences",
    scope: "Structural Works",
    group: "General Scope",
    percent: 5,
    source: "Structural drawings",
    updateMode: "Input scopes",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-009",
    projectId: "dimaano-residences",
    scope: "Architectural Works",
    group: "General Scope",
    percent: 8,
    source: "Architectural drawings",
    updateMode: "Input scopes",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-010",
    projectId: "dimaano-residences",
    scope: "MEPF Works",
    group: "General Scope",
    percent: 3,
    source: "Contract / drawings",
    updateMode: "Input scopes",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-011",
    projectId: "dimaano-residences",
    scope: "Finishes and Built-ins",
    group: "General Scope",
    percent: 0,
    source: "Architectural drawings",
    updateMode: "Input scopes",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-01",
    approvalFileUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
  },
  {
    id: "SOW-MAG-001",
    projectId: "magnolia-residences",
    scope: "Foyer",
    group: "Magnolia 8BC Scope of Work",
    percent: 8,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Copy/paste template",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-09",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-002",
    projectId: "magnolia-residences",
    scope: "Dining Area",
    group: "Magnolia 8BC Scope of Work",
    percent: 5,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Site Manager",
    approvedDate: "2026-06-09",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-003",
    projectId: "magnolia-residences",
    scope: "Kitchen",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Approved site manager scan",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-004",
    projectId: "magnolia-residences",
    scope: "Living Area",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-005",
    projectId: "magnolia-residences",
    scope: "Laundry Area",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-006",
    projectId: "magnolia-residences",
    scope: "Guest Bedroom",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-007",
    projectId: "magnolia-residences",
    scope: "Guest T&B",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-008",
    projectId: "magnolia-residences",
    scope: "Master Bedroom",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-009",
    projectId: "magnolia-residences",
    scope: "Master T&B",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
  {
    id: "SOW-MAG-010",
    projectId: "magnolia-residences",
    scope: "General",
    group: "Magnolia 8BC Scope of Work",
    percent: 0,
    source: "Magnolia 8BC_ Scope of Work",
    updateMode: "Input scopes",
    approvedBy: "Pending",
    approvedDate: "Pending",
    approvalFileUrl: "https://docs.google.com/document/d/1IRactfUow3WxKcxjlXVYqNDr8ShH7SKErwI--of2O0Q",
  },
];

export const deployedTools: DeployedTool[] = [
  {
    id: "TOOLS-MAG-001",
    projectId: "magnolia-residences",
    name: "Rotary hammer",
    folderUrl: "https://drive.google.com/",
    imageLabel: "rotary-hammer-2026-06-09.jpg",
    deployedDate: "2026-06-09",
    status: "Deployed",
  },
  {
    id: "TOOLS-MAG-002",
    projectId: "magnolia-residences",
    name: "Extension cords and site lights",
    folderUrl: "https://drive.google.com/",
    imageLabel: "site-lights-2026-06-09.jpg",
    deployedDate: "2026-06-09",
    status: "Deployed",
  },
  {
    id: "TOOLS-DIM-001",
    projectId: "dimaano-residences",
    name: "Concrete mixer",
    folderUrl: "https://drive.google.com/drive/folders/1cixh02KuVl9s314RG4_SID-DwfWUhsN4",
    imageLabel: "concrete-mixer-deployed.jpg",
    deployedDate: "2026-06-01",
    status: "Deployed",
  },
];

export function getScopeOfWorkItems(projectId: string) {
  return scopeOfWorkItems.filter((item) => item.projectId === projectId);
}

export function getDeployedTools(projectId: string) {
  return deployedTools.filter((item) => item.projectId === projectId);
}
